import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { MSWProvider } from "@/components/MSWProvider";
import { ReactQueryProvider } from "@/components/ReactQueryProvider";
import "./globals.css";

const roboto = Roboto({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${roboto.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col font-sans">
        <MSWProvider>
          <ReactQueryProvider>
            {children}
          </ReactQueryProvider>
        </MSWProvider>
      </body>
    </html>
  );
}
